# Generated by Django 4.1.5 on 2023-01-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_followers_alter_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reset',
        ),
    ]
