# Generated by Django 4.1.4 on 2022-12-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_file'),
        ('accounts', '0003_bookmark_bookmarkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkuser',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
